# -*- coding: utf-8 -*-
"""02_Fixing_Mistakes_in_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/kevin-blasiak-curtin/ISYS2001-Archive/blob/main/Module%2001/02_Fixing_Mistakes_in_Python.ipynb

# Breaking Things on Purpose

Good news: you're about to write some code that doesn't work. Also good news — that's the entire point of this notebook.

Every programmer, no matter how many years they've been at it, spends a chunk of their day staring at red error messages. The skill that actually matters isn't avoiding errors, it's reading them calmly and knowing where to look. Python is unusually generous about telling you what went wrong — you just have to get comfortable listening to it.

In this notebook, you'll deliberately run broken code, read Python's error message, and fix it. Every mistake below is one that almost everyone makes in their first week:

- Getting the capitalisation of a command wrong
- Losing a bracket or a quotation mark
- Indenting a line that shouldn't be indented
- A plain old typo

> 💡 **Advanced note:** This process of finding and fixing mistakes is called **debugging**. You'll get noticeably faster at it as the semester goes on.

## Section 4: Python Cares About Capitals

Python treats `print`, `Print`, and `PRINT` as three completely different things — and only one of them actually works. Run the code below to see the error, then fix it.
"""

PRINT("All caps")



"""> 💡 Reading tip: you won't understand every line of a Python error message, and that's normal. Skim for the parts in plain English and the line number it points to.
> 💡 **AI tip:** Confused by an error? Paste it into your AI assistant and ask it to explain what went wrong.

## Section 5: Whitespace Matters

Python uses indentation — spaces at the start of a line — to understand how your code is structured. Most other languages use brackets for this instead. Run the code below first to see the error, then fix the indentation.

"""

print("Hello")
     print("Python!")

"""> 💡 **Advanced note:** Python's error message here is called a *traceback* — it names the *exception* that occurred. We'll dig into these more later in the semester.

## Section 6: Watch Your Spelling

A single missing or swapped letter is enough to break a program. Run the code below, then fix the typo.

"""

pint("Hello, World!")

"""> 💡 **AI tip:** Stuck? Ask your AI assistant *"what's wrong with this function call?"*

## Section 7: Finish Your Quotes

Every opening quotation mark needs a matching closing one. Run the code below to see what Python does when one's missing, then fix it.

"""

print("Python)

"""## Section 8: Finish Your Brackets

The same rule applies to parentheses — every `(` needs a `)`. Fix the code below.

"""

print("I have no end"

"""> 💡 **AI tip:** If an AI's explanation goes over your head, just ask it to explain it more simply — it won't get tired of being asked twice.

## Section 9: Fix Someone Else's Code

Bob is new to Python too, and his first script has several mistakes stacked on top of each other. Find and fix all of them — there's more than one.

"""

# prinT("Good morning!"
# Print("Python is amazing!")
#     print("Let's learn Python together!"
# print("Coding is exciting")
# print("I have no idea what's going on!"

"""> 💡 **AI tip:** Ask your AI assistant *"what's wrong with this code?"*, then check its explanation against your own reading before you apply the fix.

Six errors down. You'll run into every one of these again in real projects — the difference now is you'll recognise them on sight instead of panicking.

"""
